azure:
  eventHub:
    connectionString: "Endpoint=sb://tc-eda-iac-prod-customer-eventhub.servicebus.windows.net/;SharedAccessKeyName=pubsub;SharedAccessKey=dKYC5TYAIMEa9kDGsSwPgmFgyvkoWYilaKXlUGWqOy8=;EntityPath=customerchanged"
    consumerGroup: "$Default"

server:
  port: 9080

management:
  endpoints:
    web:
      base-path: "/"
    enabled-by-default: true
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true