azure:
  eventHub:
    connectionString: ${EVENTHUBCONNECTIONSTRING}
    consumerGroup: "$Default"

server:
  port: ${SERVERPORT}

spring:
  profiles:
    active: prod

management:
  endpoints:
    web:
      base-path: "/"
    enabled-by-default: true
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true