name: Deploy Container CustomerChangedConsumer

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login using Azure Service Principal'
        uses: Azure/login@v1
        with: 
          creds: >-
            {
              "clientId":"${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret" : "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId":"${{ secrets.ARM_TENANT_ID }}" 
            }
      - name: Get Keyvault Secrets 
        uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: "myKeyVault"
          secrets: 'mySecret1, mySecret2'
        id: myGetSecretAction

      - name: Deploy to Azure Container Instancess
        uses: Azure/aci-deploy@v1
        with:
          # Name of the Resource Group in which the Container Instance will be created
          resource-group: 
          # The command line to run when the container is started, e.g. "/bin/bash -c myscript.sh"
          command-line: # optional, default is 
          # The DNS Name Label for Container with Public IP
          dns-name-label: 
          # List of environment variables for the container. Space-seperated in "key=value" format
          environment-variables: # optional, default is 
          # The target directory path in the git repository. Must not contain ".."
          gitrepo-dir: # optional, default is 
          # The path within the container where the git repo volume should be mounted. Must not contain ":"
          gitrepo-mount-path: # optional, default is 
          # The commit hash for the specified revision
          gitrepo-revision: # optional, default is 
          # The URL of a git repository to be mounted as a volume
          gitrepo-url: # optional, default is 
          # Specify the fully qualified container image name. For example, "myregistry.azurecr.io/nginx:latest" or "python:3.7.2-alpine/"
          image: 
          # Location where the Container will be deployed
          location: 
          # Name of the Container Group Instance
          name: 
          # The OS type of the Containers. Accepted Values are  { Linux, Windows }
          os-type: # optional, default is Linux
          # The Ports to Open on the Container. Space seperate the ports for multiple values
          ports: # optional, default is 80
          # The Network protocol to use. Accepted Values are { TCP, UDP }
          protocol: # optional, default is TCP
          # The container image registry login server
          registry-login-server: # optional, default is 
          # Username to log in Container Image Registry Server
          registry-username: # optional, default is 
          # Password to log in Container Image Registry Server
          registry-password: # optional, default is 
          # List of secure environment variables for the container. Space seperated values in "key=value" format
          secure-environment-variables: # optional, default is  