name: Deploy order placed consumer function

on:
  workflow_dispatch:
    inputs:
      variable_name: 
        description: Desired name of your environment
        required: true

env: #Environment Variables 
  AZURE_FUNCTIONAPP_NAME: ${{github.event.inputs.variable_name}}-order-placed-consumer  # set this to your application's environments name
  POM_FUNCTIONAPP_NAME: 'OrderPlacedConsumer'                       # set this to the function app name in your local development environment
  POM_XML_DIRECTORY: 'functions/OrderPlacedConsumer'                     # set this to the directory which contains pom.xml file
  JAVA_VERSION: '11.0.9'                                                 # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: #Step 1: Get code
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    - name: Setup Java ${{ env.JAVA_VERSION }} Environment
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: 'Restore Project Dependencies Using Mvn'
      shell: bash
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package
        popd
    - name: 'Login using Azure Service Principal'
      uses: Azure/login@v1
      with: 
        creds: >-
          {
            "clientId":"${{ secrets.ARM_CLIENT_ID }}",
            "clientSecret" : "${{ secrets.ARM_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
            "tenantId":"${{ secrets.ARM_TENANT_ID }}" 
          }
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az functionapp config set --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group tc-eda-iac-${{github.event.inputs.variable_name}} --java-version 11
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        ### Azure function name
        app-name: ${{github.event.inputs.variable_name}}-order-placed-consumer
        package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'