name: Deploy customer changed consumer function

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'functions/CustomerChangedConsumer/**' ]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: tc-eda-iac-prod-function-customer-consumer  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions/CustomerChangedConsumer'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.301'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Login using Azure Service Principal'
      uses: Azure/login@v1
      with: 
        creds: >-
          {
            "clientId":"${{ secrets.ARM_CLIENT_ID }}",
            "clientSecret" : "${{ secrets.ARM_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
            "tenantId":"${{ secrets.ARM_TENANT_ID }}" 
          }
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

